services:
  postgres:
    image: postgres:17-alpine
    container_name: wt-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: window_treatments
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
