/**
 * Alustra® Woven Textures® - Product Layout Data
 * Auto-generated from extracted PDF data (image-text-mapping.json)
 */

import type { ProductLayout, SectionLayout, SwatchCollection } from './types'

export const alustraWovenLayout: ProductLayout = {
  slug: 'alustra-woven-textures',
  name: 'Alustra® Woven Textures®',
  description: 'Created to meet the expectations of those who seek the best in design, the Alustra Collection is an exclusive, thoughtfully curated selection of woven texture fabrics with PowerView Automation capabilities.',

  heroImage: 'page002_img01_2028x1953.jpeg',
  heroLabel: 'Alustra ® Woven Textures ®',

  sections: [
    {
      type: 'scene-pair',
      scenes: [
        {
          image: 'page006_img01_2681x1953.jpeg',
          text: 'Operating System PowerView® Automation    Deck 1',
          label: 'Fabric Timberlake    Color Sun\nOperating System PowerView® Automation    Deck 1',
        },
        {
          image: 'page039_img01_3009x2427.jpeg',
          text: '',
          label: '',
        },
        {
          image: 'page040_img01_3010x3010.jpeg',
          text: '',
          label: '',
        },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'Created to meet the',
      cols: 1,
      items: [
        { image: 'page008_img02_483x1958.jpeg', label: 'Created to meet the', sublabel: 'expectations of those who seek the best in design.' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'IMAGINE. EDIT. REFINE.',
      cols: 1,
      items: [
        { image: 'page009_img02_496x1732.jpeg', label: 'IMAGINE. EDIT. REFINE.' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'LORI',
      cols: 1,
      items: [
        { image: 'page010_img03_588x610.jpeg', label: '8' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'Benefits',
      cols: 4,
      items: [
        { image: 'page018_img01_1056x681.jpeg', label: 'Benefits', sublabel: 'Innovative Fabric Collection A custom curated collection of globally sourced fabrics with sumptuous textures designed to filter light' },
        { image: 'page018_img02_1055x680.jpeg', label: 'Opacity & Light Control Options', sublabel: 'Fabrics in this collection feature varying levels of opacity from sheer to semi-opaque. In addition, the Roller Duolite® Shade, Dual Roller and Roman Shade with Independent Operable Liner allow you to' },
        { image: 'page018_img03_1052x675.jpeg', label: 'Three Product Styles', sublabel: 'The fabrics in this collection are available as Roman Shades, Roller Shades and Skyline® Panels. Use together for a Whole House Solution or separately to finish any room with style and functionality.' },
        { image: 'page018_img04_1055x680.jpeg', label: 'PowerView® Automation', sublabel: 'PowerView® Automation provides the ultimate in home automation allowing you to control every shade with the touch of a button.' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'One Fabric Collection',
      cols: 4,
      items: [
        { image: 'page019_img01_1015x1955.jpeg', label: 'One Fabric Collection', sublabel: 'Three Product Styles Roman Shades' },
        { image: 'page019_img02_757x626.jpeg', label: 'Roller Shade', sublabel: 'understated yet sophisticated elegance. Roman Shades' },
        { image: 'page019_img03_741x626.jpeg', label: 'Roller Shade', sublabel: 'The modern minimalistic style and simple lines of a roller shade creates an understated yet sophisticated elegance.' },
        { image: 'page019_img04_675x636.jpeg', label: 'Skyline® Panels', sublabel: 'Cover both windows and doors with the sleek look of Skyline® Panels. This exclusive system provides a contemporary design aesthetic.' },
      ],
    },
    {
      type: 'split-scene',
      title: 'Refined Dimension',
      sceneImage: 'page020_img02_1762x1536.jpeg',
      sceneLabel: 'Refined Dimension',
      sceneSide: 'left',
      items: [
        { image: 'page020_img01_833x868.jpeg', label: 'Refined Dimension', sublabel: 'Specialty Features' },
        { image: 'page020_img03_646x670.jpeg', label: 'Optimizes Privacy & Light Control', sublabel: 'This feature provides a more versatile approach to light control. Open from the top or from the bottom, or find somewhere in between for the' },
        { image: 'page020_img04_647x671.jpeg', label: 'Two Shades, One Headrail', sublabel: 'From soft, filtered light to total light control and privacy, the independent liner option provides complete versatility and ultimate' },
      ],
    },
    {
      type: 'split-scene',
      title: 'Minimalistic Perspective',
      sceneImage: 'page021_img02_1703x1537.jpeg',
      sceneLabel: 'Minimalistic Perspective',
      sceneSide: 'right',
      items: [
        { image: 'page021_img01_816x868.jpeg', label: 'Minimalistic Perspective', sublabel: 'Specialty Features' },
        { image: 'page021_img03_647x672.jpeg', label: 'One Shade Solution', sublabel: 'Roller Duolite® Shade' },
        { image: 'page021_img04_646x671.jpeg', label: 'Two Roller Shades, One Window', sublabel: 'Two Roller Shades, One Window' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'Roman Shade',
      cols: 4,
      items: [
        { image: 'page024_img01_942x1952.jpeg', label: 'Independent Operable Liner', sublabel: 'The freedom to turn into a light-filtering or' },
        { image: 'page024_img02_479x623.jpeg', label: 'Available with the following operating systems: PowerView® Automation, UltraGlide®, LiteRise® and EasyRise™.', sublabel: 'Systems will be the same for both shade and liner. Liner Shade Fabric Lowered' },
        { image: 'page024_img03_479x623.jpeg', label: 'Available with the following operating systems: PowerView® Automation, UltraGlide®, LiteRise® and EasyRise™.', sublabel: 'Liner Shade Fabric Partially Raised Liner Shade Fabric Fully Raised' },
        { image: 'page024_img04_479x624.jpeg', label: 'Liner Shade Fabric Fully Raised' },
        { image: 'page024_img05_479x623.jpeg', label: 'Light-Filtering Liner', sublabel: 'Diffuses light for a soft glow while providing moderate privacy.' },
        { image: 'page024_img06_479x623.jpeg', label: '37', sublabel: 'Room-Darkening Liner Provides enhanced light control with' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'Roller Duolite® Shade',
      cols: 4,
      items: [
        { image: 'page025_img01_943x1959.jpeg', label: 'Roller Duolite® Shade', sublabel: 'Combine a sheer or semi-sheer fabric with' },
        { image: 'page025_img02_479x622.jpeg', label: 'Front Fabric Fully Lowered', sublabel: 'Back Liner Not Lowered Front Fabric Fully Lowered' },
        { image: 'page025_img03_479x622.jpeg', label: 'Front Fabric Fully Lowered', sublabel: 'Back Liner Partially Lowered Front Fabric Fully Lowered' },
        { image: 'page025_img04_479x623.jpeg', label: 'Front Fabric Fully Lowered', sublabel: 'Back Liner Fully Lowered' },
        { image: 'page025_img05_479x511.jpeg', label: 'Room-Darkening Liner', sublabel: 'Provides enhanced light control with maximum privacy.' },
        { image: 'page025_img06_479x512.jpeg', label: 'One Shade', sublabel: 'The front fabric and liner are on the same roll providing a minimal profile.' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'Dual Roller',
      cols: 4,
      items: [
        { image: 'page026_img01_944x1953.jpeg', label: 'Fabric Retreat    Color Cabana', sublabel: 'Operating System Dual Roller Shade with PowerView® Automation    Deck 1 Woven Texture® Fabric' },
        { image: 'page026_img02_479x623.jpeg', label: 'Front Shade and Back Liner Lowered', sublabel: 'with PowerView® Automation and Custom Clutch operating systems. Optional valance design feature available.' },
        { image: 'page026_img03_479x623.jpeg', label: 'Front Shade, Back Liner Partially Lowered', sublabel: 'Two shades combined together with one Woven Textures positioned in front. Front shade is reverse roll, back shade is standard roll. Available with PowerView® Automation and Custom Clutch operating systems. Optional valance design feature available.' },
        { image: 'page026_img04_479x623.jpeg', label: 'Front Shade Lowered, Back Liner Fully Raised' },
        { image: 'page026_img05_475x525.jpeg', label: 'Light-Filtering Liner', sublabel: 'Diffuses light for a soft glow while providing moderate privacy.' },
        { image: 'page026_img06_475x525.jpeg', label: 'Room-Darkening Liner', sublabel: 'Provides enhanced light control with maximum privacy.' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'PowerView® Automation',
      cols: 4,
      items: [
        { image: 'page027_img01_944x1955.jpeg', label: 'PowerView® Automation', sublabel: 'Program shadings to be in the best positions throughout Remote control gives the illusion that you\'re always home' },
        { image: 'page027_img02_321x556.jpeg', label: 'Convenience', sublabel: 'Achieve your perfect light automatically Privacy' },
        { image: 'page027_img03_216x458.jpeg', label: 'Convenience', sublabel: 'Achieve your perfect light automatically Privacy' },
        { image: 'page027_img04_416x669.jpeg', label: '' },
        { image: 'page027_img05_259x551.jpeg', label: '' },
        { image: 'page027_img06_471x341.jpeg', label: '' },
        { image: 'page027_img08_509x394.jpeg', label: '' },
        { image: 'page027_img09_471x341.jpeg', label: '' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'PowerView® Automation',
      cols: 4,
      items: [
        { image: 'page028_img01_962x1955.jpeg', label: 'PowerView® Automation', sublabel: 'Program shadings to be in the best positions throughout Remote control gives the illusion that you\'re always home' },
        { image: 'page028_img04_321x556.jpeg', label: 'Convenience', sublabel: 'Achieve your perfect light automatically Privacy' },
        { image: 'page028_img05_216x458.jpeg', label: 'Convenience', sublabel: 'Achieve your perfect light automatically Privacy' },
        { image: 'page028_img08_711x602.jpeg', label: '10:30 PM Bedtime', sublabel: 'Shades lower automatically for privacy and a perfect night\'s sleep.' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'Operating Systems',
      cols: 4,
      items: [
        { image: 'page029_img01_416x669.jpeg', label: 'UltraGlide®', sublabel: 'PowerView® Automation Smoothly integrates with other smart-home' },
        { image: 'page029_img02_259x551.jpeg', label: 'UltraGlide®', sublabel: 'PowerView® Automation Smoothly integrates with other smart-home' },
        { image: 'page029_img03_471x341.jpeg', label: 'UltraGlide®', sublabel: 'The revolutionary retractable cord with constant cord length provides enhanced safety.' },
        { image: 'page029_img04_469x555.jpeg', label: 'Independent Operable Liner', sublabel: 'Duo Liner: • Color faces room, white faces street' },
        { image: 'page029_img05_469x559.jpeg', label: 'Top-Down/Bottom-Up', sublabel: 'This shade feature offers a more versatile approach to light control. Open from the top or' },
        { image: 'page029_img07_509x394.jpeg', label: 'LiteRise®', sublabel: 'The cordless system makes raising and lowering the shade easy. Simply push up to raise and pull down to' },
        { image: 'page029_img08_471x398.jpeg', label: 'Two-On-One-Headrail', sublabel: 'The solution for extra wide windows and side by side windows. A single headrail provides a clean look' },
        { image: 'page029_img09_471x341.jpeg', label: 'EasyRise®', sublabel: 'Raise or lower the shade with a continuous cord loop. A universal cord tensioner attaches to the' },
      ],
    },
    {
      type: 'card-grid',
      title: 'Top Treatments',
      cols: 4,
      cards: [
        { image: 'page030_img01_471x570.jpeg', title: 'Headrail with Valance', desc: 'Available with the following operating systems: UltraGlide®, LiteRise®, EasyRise®. Valance height options: 6 ½", 8", 12", 16". EasyRise.' },
        { image: 'page030_img02_471x570.jpeg', title: 'Fabric-covered Headrail without Valance', desc: 'Available with the following operating systems: PowerView® Automation, UltraGlide, LiteRise, EasyRise.' },
        { image: 'page030_img03_472x571.jpeg', title: 'Fabric Wrapped Standard Bar', desc: 'Available with all operating systems. Fabric Wrapped Flat Bar Available with UltraGlide and EasyRise operating systems.' },
        { image: 'page030_img04_472x571.jpeg', title: 'Fabric Wrapped Flat Bar', desc: 'Available with UltraGlide and EasyRise operating systems.' },
        { image: 'page030_img05_471x570.jpeg', title: 'Stand-Alone Valance', desc: 'Option The fabric-wrapped valance provides a structured and tailored profile. Valance height options: 6 ½", 8".' },
        { image: 'page030_img06_471x570.jpeg', title: 'Flat Metal Bar', desc: 'Available with UltraGlide and EasyRise operating systems. Sewn in Hem and EasyRise operating systems.' },
        { image: 'page030_img07_471x570.jpeg', title: 'Sewn in Hem', desc: 'Available with PowerView Automation, UltraGlide and EasyRise operating systems.' },
      ],
    },
    {
      type: 'card-grid',
      title: 'Top Treatments',
      cols: 4,
      cards: [
        { image: 'page032_img01_472x319.jpeg', title: 'Small Square Cassette 2.0', desc: 'Conceals the fabric roll behind a modern, square fabric-wrapped cover. Available with the following operating systems: PowerView Automation, Custom Clutch, SoftTouch Motorization.' },
        { image: 'page032_img02_470x319.jpeg', title: 'Large Square Cassette 2.0', desc: 'Conceals the fabric roll behind a modern, square fabric- wrapped cover. Available with the following operating systems: PowerView® Automation, Custom Clutch, UltraGlide®, LiteRise®, SoftTouch Motorization.' },
        { image: 'page032_img03_470x320.jpeg', title: 'Fabric-Wrapped Standard Bar', desc: 'Available with all the operating systems. Fabric-Wrapped Flat Bar Clutch, UltraGlide, SoftTouch.' },
        { image: 'page032_img04_468x317.jpeg', title: 'Fabric-Wrapped Flat Bar', desc: 'Available with PowerView Automation, Custom Clutch, UltraGlide, SoftTouch.' },
        { image: 'page032_img05_471x319.jpeg', title: '4" Fascia', desc: 'The exposed metal valance covers the fabric roll providing an upscale, sleek contemporary look. Color options include 10 Custom Hardware Colors and Anodized. Available with the following operating' },
        { image: 'page032_img06_472x320.jpeg', title: '5¼" Pocket', desc: 'The fabric roll and operating system is completely enclosed and recessed into the ceiling. Color options include Anodized and White Tiara. Available with the following operating systems: PowerView' },
        { image: 'page032_img07_469x319.jpeg', title: 'Flat Metal Bar', desc: 'Available with PowerView Automation, Custom Clutch, UltraGlide. Sewn In Hem Available with Custom Clutch.' },
        { image: 'page032_img08_470x319.jpeg', title: 'Sewn In Hem', desc: 'Available with Custom Clutch.' },
        { image: 'page032_img09_472x319.jpeg', title: 'Stand-Alone Valance', desc: 'The fabric-wrapped valance provides a structured and tailored profile. Valance length options: 6½", 8".' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'Expert Design',
      cols: 3,
      items: [
        { image: 'page037_img01_483x452.jpeg', label: '' },
        { image: 'page037_img02_483x454.jpeg', label: '' },
        { image: 'page037_img03_483x454.jpeg', label: '' },
      ],
    },
  ],

  gallery: [
    { image: 'page002_img01_2028x1953.jpeg', text: '\', label: \'' },
    { image: 'page006_img01_2681x1953.jpeg', text: 'Operating System PowerView® Automation  ', label: 'Fabric Timberlake    Color Sun\nOperating System PowerView® Automation    Deck 1' },
    { image: 'page008_img01_1641x1954.jpeg', text: '4 Created to meet the expectations of th', label: '' },
    { image: 'page008_img03_1777x1955.jpeg', text: 'Created to meet the expectations of thos', label: '' },
    { image: 'page009_img01_1280x1734.jpeg', text: 'IMAGINE. EDIT. REFINE. 6', label: '' },
    { image: 'page009_img03_1795x1732.jpeg', text: 'IMAGINE. EDIT. REFINE. Inspired from des', label: 'Fabric Ramble by Lori Weitzner    Color Silver' },
    { image: 'page010_img01_1778x1955.jpeg', text: 'Lori Weitzner is a leading international', label: '' },
    { image: 'page010_img02_1798x1770.jpeg', text: 'Lori Weitzner is a leading international', label: '' },
    { image: 'page020_img02_1762x1536.jpeg', text: '28 Refined Dimension Specialty Features', label: 'Fabric Highlands by Lori Weitzner    Color Parchment\nOperating System PowerView® Automation    Deck 2' },
    { image: 'page021_img02_1703x1537.jpeg', text: '30 Minimalistic Perspective Specialty Fe', label: 'Fabric Retreat    Color Pure\nOperating System PowerView® Automation    Deck 1' },
    { image: 'page027_img07_1269x1243.jpeg', text: '\', label: \'Fabric Plantation    Color Dynasty\nOperating System PowerView® Automation    Deck 2' },
    { image: 'page028_img02_1696x1955.jpeg', text: '7:00 AM Morning Schedule shades to let i', label: '' },
  ],

  hardwareColors: {
    type: 'hardware-colors',
    title: 'Hardware Color Guide',
    brandLabel: 'Alustra® Woven Textures®',
    items: [
      { image: 'page045_img01_306x306.jpeg', label: '048 Black' },
      { image: 'page045_img02_306x306.jpeg', label: '048 Black' },
      { image: 'page045_img03_306x306.jpeg', label: '048 Black' },
      { image: 'page045_img04_306x306.jpeg', label: '064 Bronze' },
      { image: 'page045_img05_306x306.jpeg', label: '235 Gold' },
      { image: 'page045_img06_306x306.jpeg', label: '316 Nickel' },
      { image: 'page045_img07_306x306.jpeg', label: '320 Rich Cream' },
      { image: 'page045_img08_306x306.jpeg', label: '651 Duchess Grey' },
      { image: 'page045_img09_306x306.jpeg', label: '879 Pearl Gray' },
      { image: 'page045_img10_306x306.jpeg', label: '879 Pearl Gray' },
    ],
  },

  swatchCollections: [
    {
      name: 'Fabrics',
      swatches: [
        { image: 'page005_img01_1800x1953.jpeg', colorName: '', specs: [] },
        { image: 'page005_img02_918x1953.jpeg', colorName: '', specs: [] },
        { image: 'page007_img01_1820x1958.jpeg', colorName: 'A LOOK. A FEEL. ALUSTRA', specs: ['®', '2'] },
        { image: 'page007_img02_1795x1958.jpeg', colorName: '®', specs: ['3'] },
        { image: 'page012_img01_1787x1956.jpeg', colorName: 'Fabric Artisan    Color Calligraphy', specs: ['Operating System PowerView® Automation    Deck 2', '12'] },
        { image: 'page012_img02_1777x1956.jpeg', colorName: '13', specs: [] },
        { image: 'page013_img01_940x1956.jpeg', colorName: 'Fabric Coppice by Lori Weitzner    Color Sunrise', specs: ['Operating System Independent Operable Liner with PowerView® Automation    Deck 1', 'Design Studio™ Side Panels Fabric Hudson    Color Sandy Beach    Liner Room-Darkening', 'Roman Shades paired', 'with Design Studio™'] },
        { image: 'page013_img02_1776x1956.jpeg', colorName: 'Fabric Coppice by Lori Weitzner    Color Sunrise', specs: ['Operating System Independent Operable Liner with PowerView® Automation    Deck 1', 'Design Studio™ Side Panels Fabric Hudson    Color Sandy Beach    Liner Room-Darkening', '15'] },
        { image: 'page014_img01_1794x1952.jpeg', colorName: '16', specs: [] },
        { image: 'page014_img02_1794x1952.jpeg', colorName: 'Fabric Retreat    Color Cabana', specs: ['Operating System Dual Roller with PowerView® Automation    Deck 1', '17'] },
        { image: 'page015_img01_961x1952.jpeg', colorName: 'Shades provide the', specs: ['control and privacy', 'Fabric Arusha    Color Journey', 'Operating System Duolite® with PowerView® Automation    Deck 1'] },
        { image: 'page015_img02_1793x1952.jpeg', colorName: 'Fabric Arusha    Color Journey', specs: ['Operating System Duolite® with PowerView® Automation    Deck 1', '19'] },
        { image: 'page016_img01_1797x1953.jpeg', colorName: 'Fabric Lisban    Color Heritage', specs: ['Operating System PowerView® Automation    Deck 2', '20'] },
        { image: 'page016_img02_1797x1953.jpeg', colorName: '21', specs: ['21'] },
        { image: 'page017_img01_981x1957.jpeg', colorName: 'A refined approach', specs: ['for expansive spaces.', 'Woven Textures®', 'create a striking', 'contemporary look.'] },
        { image: 'page017_img02_1795x1957.jpeg', colorName: 'Fabric Rivulet by Lori Weitzner    Color Silt', specs: ['Operating System PowerView® Automation    Deck 1', '23'] },
        { image: 'page036_img01_1749x1880.jpeg', colorName: 'Fabric Primitive    Color Concrete', specs: ['Operating System PowerView® Automation    Deck 2', '58'] },
        { image: 'page046_img01_632x1050.jpeg', colorName: 'SNOW', specs: ['Sheer RMB-100', 'SILVER'] },
        { image: 'page046_img02_632x1050.jpeg', colorName: 'Sheer RMB-100', specs: ['SILVER', 'Sheer RMB-300', '1'] },
        { image: 'page047_img01_632x1050.jpeg', colorName: 'PEWTER', specs: ['Sheer RMB-800'] },
        { image: 'page048_img01_632x1050.jpeg', colorName: 'WHISP', specs: ['Sheer COP-700', 'FLINT'] },
        { image: 'page048_img02_632x1050.jpeg', colorName: 'Sheer COP-700', specs: ['FLINT', 'Sheer COP-800', '3'] },
        { image: 'page049_img01_632x1050.jpeg', colorName: 'SUNRISE', specs: ['Sheer COP-350'] },
        { image: 'page050_img01_632x1050.jpeg', colorName: 'JOURNEY', specs: ['Sheer ARU-300', 'PLATEAU'] },
        { image: 'page050_img02_632x1050.jpeg', colorName: 'Sheer ARU-300', specs: ['PLATEAU', 'Sheer ARU-301', '5'] },
        { image: 'page051_img01_632x1050.jpeg', colorName: 'PATH', specs: ['Sheer ARU-400', 'BOUNDLESS'] },
        { image: 'page051_img02_632x1050.jpeg', colorName: 'Sheer ARU-400', specs: ['BOUNDLESS', 'Sheer ARU-800', '6'] },
        { image: 'page052_img01_632x1050.jpeg', colorName: 'WHITE SAIL', specs: ['Semi-Sheer CPR-100', 'PARADISE'] },
        { image: 'page052_img02_632x1050.jpeg', colorName: 'Semi-Sheer CPR-100', specs: ['PARADISE', 'Semi-Sheer CPR-200', '7'] },
        { image: 'page053_img01_632x1050.jpeg', colorName: 'BREEZE', specs: ['Semi-Sheer CPR-800', 'BUNGALOW'] },
        { image: 'page053_img02_632x1050.jpeg', colorName: 'Semi-Sheer CPR-800', specs: ['BUNGALOW', 'Semi-Sheer CPR-801', '8'] },
        { image: 'page054_img01_632x1050.jpeg', colorName: 'HAMMOCK', specs: ['Semi-Sheer CPR-400'] },
        { image: 'page055_img01_632x1050.jpeg', colorName: 'CAPELLA', specs: ['Semi-Sheer LYR-100', 'HARMONY'] },
        { image: 'page055_img02_632x1050.jpeg', colorName: 'Semi-Sheer LYR-100', specs: ['HARMONY', 'Semi-Sheer LYR-200', '10'] },
        { image: 'page056_img01_632x1050.jpeg', colorName: 'CAPRICE', specs: ['Semi-Sheer LYR-800', 'CANTATA'] },
        { image: 'page056_img02_632x1050.jpeg', colorName: 'Semi-Sheer LYR-800', specs: ['CANTATA', 'Semi-Sheer LYR-700', '11'] },
        { image: 'page057_img01_632x1050.jpeg', colorName: 'PAPYRUS', specs: ['Semi-Sheer TBL-200', 'SUN'] },
        { image: 'page057_img02_632x1050.jpeg', colorName: 'Semi-Sheer TBL-200', specs: ['SUN', 'Semi-Sheer TBL-300', '12'] },
        { image: 'page058_img01_632x1050.jpeg', colorName: 'HONEY', specs: ['Semi-Sheer TBL-402', 'TOASTED PECAN'] },
        { image: 'page058_img02_632x1050.jpeg', colorName: 'Semi-Sheer TBL-402', specs: ['TOASTED PECAN', 'Semi-Sheer TBL-401', '13'] },
        { image: 'page059_img01_632x1050.jpeg', colorName: 'COCOA', specs: ['Semi-Sheer TBL-400'] },
        { image: 'page060_img01_632x1050.jpeg', colorName: 'SOAPSTONE', specs: ['Semi-Sheer RVL-300', 'BUTTERSCOTCH'] },
        { image: 'page060_img02_632x1050.jpeg', colorName: 'Semi-Sheer RVL-300', specs: ['BUTTERSCOTCH', 'Semi-Sheer RVL-400', '15'] },
        { image: 'page061_img01_632x1050.jpeg', colorName: 'SILT', specs: ['Semi-Sheer RVL-700'] },
        { image: 'page062_img01_632x1050.jpeg', colorName: 'PURE', specs: ['Semi-Sheer RE-101', 'COZY'] },
        { image: 'page062_img02_632x1050.jpeg', colorName: 'Semi-Sheer RE-101', specs: ['COZY', 'Semi-Sheer RE-300', '17'] },
        { image: 'page063_img01_632x1050.jpeg', colorName: 'JOY', specs: ['Semi-Sheer RE-800', 'CABANA'] },
        { image: 'page063_img02_632x1050.jpeg', colorName: 'Semi-Sheer RE-800', specs: ['CABANA', 'Semi-Sheer RE-400', '18'] },
        { image: 'page064_img01_632x1050.jpeg', colorName: 'GLASSINE', specs: ['Semi-Sheer FO-100', 'ABALONE'] },
        { image: 'page064_img02_632x1050.jpeg', colorName: 'Semi-Sheer FO-100', specs: ['ABALONE', 'Semi-Sheer FO-822', '19'] },
        { image: 'page065_img01_632x1050.jpeg', colorName: 'SHUTTER', specs: ['Semi-Sheer FO-800', 'CAFE'] },
        { image: 'page065_img02_632x1050.jpeg', colorName: 'Semi-Sheer FO-800', specs: ['CAFE', 'Semi-Sheer FO-329', '20'] },
        { image: 'page066_img01_632x1050.jpeg', colorName: 'CAVIAR', specs: ['Semi-Sheer FO-900'] },
        { image: 'page067_img01_632x1050.jpeg', colorName: 'TIN', specs: ['Semi-Sheer LC-307', 'CHROME'] },
        { image: 'page067_img02_632x1050.jpeg', colorName: 'Semi-Sheer LC-307', specs: ['CHROME', 'Semi-Sheer LC-805', '22'] },
        { image: 'page068_img01_632x1050.jpeg', colorName: 'PARCHMENT', specs: ['Semi-Opaque HLD-200', 'LATTE'] },
        { image: 'page068_img02_632x1050.jpeg', colorName: 'Semi-Opaque HLD-200', specs: ['LATTE', 'Semi-Opaque HLD-300', '23'] },
        { image: 'page069_img01_632x1050.jpeg', colorName: 'BROWN SUGAR', specs: ['Semi-Opaque HLD-400'] },
        { image: 'page070_img01_632x1050.jpeg', colorName: 'CHATEAU', specs: ['Semi-Opaque PLN-100', 'NOBLE'] },
        { image: 'page070_img02_632x1050.jpeg', colorName: 'Semi-Opaque PLN-100', specs: ['NOBLE', 'Semi-Opaque PLN-800', '25'] },
        { image: 'page071_img01_632x1050.jpeg', colorName: 'DYNASTY', specs: ['Semi-Opaque PLN-801', 'MONARCH'] },
        { image: 'page071_img02_632x1050.jpeg', colorName: 'Semi-Opaque PLN-801', specs: ['MONARCH', 'Semi-Opaque PLN-300', '26'] },
        { image: 'page072_img01_632x1050.jpeg', colorName: 'COFFEE', specs: ['Semi-Opaque PLN-400'] },
        { image: 'page073_img01_632x1050.jpeg', colorName: 'CANVAS', specs: ['Semi-Opaque ASN-300', 'BATIK'] },
        { image: 'page073_img02_632x1050.jpeg', colorName: 'Semi-Opaque ASN-300', specs: ['BATIK', 'Semi-Opaque ASN-800', '28'] },
        { image: 'page074_img01_632x1050.jpeg', colorName: 'SCULPT', specs: ['Semi-Opaque ASN-400', 'CALLIGRAPHY'] },
        { image: 'page074_img02_632x1050.jpeg', colorName: 'Semi-Opaque ASN-400', specs: ['CALLIGRAPHY', 'Semi-Opaque ASN-900', '29'] },
        { image: 'page075_img01_632x1050.jpeg', colorName: 'COBBLESTONE', specs: ['Semi-Opaque LSB-300', 'COACH'] },
        { image: 'page075_img02_632x1050.jpeg', colorName: 'Semi-Opaque LSB-300', specs: ['COACH', 'Semi-Opaque LSB-800', '30'] },
        { image: 'page076_img01_632x1050.jpeg', colorName: 'SUNSET', specs: ['Semi-Opaque LSB-400', 'CARRIAGE'] },
        { image: 'page076_img02_632x1050.jpeg', colorName: 'Semi-Opaque LSB-400', specs: ['CARRIAGE', 'Semi-Opaque LSB-401', '31'] },
        { image: 'page077_img01_632x1050.jpeg', colorName: 'HERITAGE', specs: ['Semi-Opaque LSB-900'] },
        { image: 'page078_img01_632x1050.jpeg', colorName: 'WHITEWASHED', specs: ['Semi-Opaque PM-206', 'CONCRETE'] },
        { image: 'page078_img02_632x1050.jpeg', colorName: 'Semi-Opaque PM-206', specs: ['CONCRETE', 'Semi-Opaque PM-205', '33'] },
        { image: 'page079_img01_632x1050.jpeg', colorName: 'VINTAGE', specs: ['Semi-Opaque PM-300', 'WEATHERVANE'] },
        { image: 'page079_img02_632x1050.jpeg', colorName: 'Semi-Opaque PM-300', specs: ['WEATHERVANE', 'Semi-Opaque PM-404', '34'] },
        { image: 'page080_img01_632x1050.jpeg', colorName: 'WHITE OAK', specs: ['Semi-Opaque EN-200', 'BIRCH'] },
        { image: 'page080_img02_632x1050.jpeg', colorName: 'Semi-Opaque EN-200', specs: ['BIRCH', 'Semi-Opaque EN-802', '35'] },
        { image: 'page081_img01_632x1050.jpeg', colorName: 'BRANCH', specs: ['Semi-Opaque EN-302', 'TWIG'] },
        { image: 'page081_img02_632x1050.jpeg', colorName: 'Semi-Opaque EN-302', specs: ['TWIG', 'Semi-Opaque EN-351', '36'] },
        { image: 'page082_img01_632x1050.jpeg', colorName: 'RAFFIA', specs: ['Semi-Opaque ON-439', 'PALM'] },
        { image: 'page082_img02_632x1050.jpeg', colorName: 'Semi-Opaque ON-439', specs: ['PALM', 'Semi-Opaque ON-701', '37'] },
        { image: 'page083_img01_632x1050.jpeg', colorName: 'SIENNA', specs: ['Semi-Opaque ON-422', 'RE-BARK'] },
        { image: 'page083_img02_632x1050.jpeg', colorName: 'Semi-Opaque ON-422', specs: ['RE-BARK', 'Semi-Opaque ON-402', '38'] },
        { image: 'page084_img01_632x1050.jpeg', colorName: 'SLATE', specs: ['Semi-Opaque ON-601'] },
        { image: 'page085_img01_632x1050.jpeg', colorName: 'BEACH', specs: ['Semi-Opaque CQ-202', 'FEATHER', 'DISCONTINUED'] },
        { image: 'page085_img02_632x1050.jpeg', colorName: 'Semi-Opaque CQ-202', specs: ['FEATHER', 'Semi-Opaque CQ-806', '40', 'DISCONTINUED'] },
      ],
    },
  ],

  cellSize: null,
  opacity: null,
  edgeBanding: null,
  liner: null,
}
