/**
 * Alustra® Woven Textures® - Product Layout Data
 * Auto-generated from extracted PDF data (image-text-mapping.json)
 */

import type { ProductLayout, SectionLayout, SwatchCollection } from './types'

export const alustraWovenLayout: ProductLayout = {
  slug: 'alustra-woven-textures',
  name: 'Alustra® Woven Textures®',
  description: 'Created to meet the expectations of those who seek the best in design, the Alustra Collection is an exclusive, thoughtfully curated selection of woven texture fabrics with PowerView Automation capabilities.',

  heroImage: 'page002_img01_2028x1953.jpeg',
  heroLabel: 'Alustra ® Woven Textures ®',

  sections: [
    {
      type: 'scene-pair',
      scenes: [
        {
          image: 'page006_img01_2681x1953.jpeg',
          text: 'Fabric Timberlake · Color Sun',
          label: 'Fabric Timberlake · Color Sun\nOperating System PowerView® Automation · Deck 1',
        },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'Benefits',
      cols: 4,
      items: [
        { image: 'page018_img01_1056x681.jpeg', label: 'Innovative Fabric Collection', sublabel: 'A custom curated collection of globally sourced fabrics with sumptuous textures designed to filter light beautifully.' },
        { image: 'page018_img02_1055x680.jpeg', label: 'Opacity & Light Control Options', sublabel: 'Fabrics in this collection feature varying levels of opacity from sheer to semi-opaque. The Roller Duolite® Shade, Dual Roller and Roman Shade with Independent Operable Liner provide complete versatility.' },
        { image: 'page018_img03_1052x675.jpeg', label: 'Three Product Styles', sublabel: 'The fabrics in this collection are available as Roman Shades, Roller Shades and Skyline® Panels. Use together for a Whole House Solution or separately to finish any room with style and functionality.' },
        { image: 'page018_img04_1055x680.jpeg', label: 'PowerView® Automation', sublabel: 'PowerView® Automation provides the ultimate in home automation allowing you to control every shade with the touch of a button.' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'One Fabric Collection',
      cols: 4,
      items: [
        { image: 'page019_img01_1015x1955.jpeg', label: 'Three Product Styles', sublabel: 'One curated fabric collection available as Roman Shades, Roller Shades, and Skyline® Panels.' },
        { image: 'page019_img02_757x626.jpeg', label: 'Roman Shades', sublabel: 'Soft, cascading folds create an elegant look with refined dimension and texture.' },
        { image: 'page019_img03_741x626.jpeg', label: 'Roller Shades', sublabel: 'The modern minimalistic style and simple lines of a roller shade create an understated yet sophisticated elegance.' },
        { image: 'page019_img04_675x636.jpeg', label: 'Skyline® Panels', sublabel: 'Cover both windows and doors with the sleek look of Skyline® Panels. This exclusive system provides a contemporary design aesthetic.' },
      ],
    },
    {
      type: 'split-scene',
      title: 'Refined Dimension',
      sceneImage: 'page020_img02_1762x1536.jpeg',
      sceneLabel: 'Refined Dimension',
      sceneSide: 'left',
      items: [
        { image: 'page020_img01_833x868.jpeg', label: 'Refined Dimension', sublabel: 'Specialty Features' },
        { image: 'page020_img03_646x670.jpeg', label: 'Optimizes Privacy & Light Control', sublabel: 'This feature provides a more versatile approach to light control. Open from the top or from the bottom, or find somewhere in between for the perfect balance.' },
        { image: 'page020_img04_647x671.jpeg', label: 'Two Shades, One Headrail', sublabel: 'From soft, filtered light to total light control and privacy, the independent liner option provides complete versatility and ultimate convenience.' },
      ],
    },
    {
      type: 'split-scene',
      title: 'Minimalistic Perspective',
      sceneImage: 'page021_img02_1703x1537.jpeg',
      sceneLabel: 'Minimalistic Perspective',
      sceneSide: 'right',
      items: [
        { image: 'page021_img01_816x868.jpeg', label: 'Minimalistic Perspective', sublabel: 'Specialty Features' },
        { image: 'page021_img03_647x672.jpeg', label: 'Roller Duolite® Shade', sublabel: 'One shade solution combining a sheer fabric with a room-darkening liner on a single roller.' },
        { image: 'page021_img04_646x671.jpeg', label: 'Dual Roller Shade', sublabel: 'Two roller shades on one window for layered light control and privacy.' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'Roman Shade',
      cols: 4,
      items: [
        { image: 'page024_img01_942x1952.jpeg', label: 'Independent Operable Liner', sublabel: 'The freedom to pair your shade with a light-filtering or room-darkening liner for complete control.' },
        { image: 'page024_img02_479x623.jpeg', label: 'Available with the following operating systems: PowerView® Automation, UltraGlide®, LiteRise® and EasyRise™.', sublabel: 'Systems will be the same for both shade and liner. Liner Shade Fabric Lowered' },
        { image: 'page024_img03_479x623.jpeg', label: 'Available with the following operating systems: PowerView® Automation, UltraGlide®, LiteRise® and EasyRise™.', sublabel: 'Liner Shade Fabric Partially Raised Liner Shade Fabric Fully Raised' },
        { image: 'page024_img04_479x624.jpeg', label: 'Liner Shade Fabric Fully Raised' },
        { image: 'page024_img05_479x623.jpeg', label: 'Light-Filtering Liner', sublabel: 'Diffuses light for a soft glow while providing moderate privacy.' },
        { image: 'page024_img06_479x623.jpeg', label: 'Room-Darkening Liner', sublabel: 'Provides enhanced light control with maximum privacy.' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'Roller Duolite® Shade',
      cols: 4,
      items: [
        { image: 'page025_img01_943x1959.jpeg', label: 'Roller Duolite® Shade', sublabel: 'Combine a sheer or semi-sheer fabric with a room-darkening liner on a single roller for layered light control.' },
        { image: 'page025_img02_479x622.jpeg', label: 'Front Fabric Fully Lowered', sublabel: 'Back Liner Not Lowered Front Fabric Fully Lowered' },
        { image: 'page025_img03_479x622.jpeg', label: 'Front Fabric Fully Lowered', sublabel: 'Back Liner Partially Lowered Front Fabric Fully Lowered' },
        { image: 'page025_img04_479x623.jpeg', label: 'Front Fabric Fully Lowered', sublabel: 'Back Liner Fully Lowered' },
        { image: 'page025_img05_479x511.jpeg', label: 'Room-Darkening Liner', sublabel: 'Provides enhanced light control with maximum privacy.' },
        { image: 'page025_img06_479x512.jpeg', label: 'One Shade', sublabel: 'The front fabric and liner are on the same roll providing a minimal profile.' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'Dual Roller',
      cols: 4,
      items: [
        { image: 'page026_img01_944x1953.jpeg', label: 'Fabric Retreat    Color Cabana', sublabel: 'Operating System Dual Roller Shade with PowerView® Automation    Deck 1 Woven Texture® Fabric' },
        { image: 'page026_img02_479x623.jpeg', label: 'Front Shade and Back Liner Lowered', sublabel: 'with PowerView® Automation and Custom Clutch operating systems. Optional valance design feature available.' },
        { image: 'page026_img03_479x623.jpeg', label: 'Front Shade, Back Liner Partially Lowered', sublabel: 'Two shades combined together with one Woven Textures positioned in front. Front shade is reverse roll, back shade is standard roll. Available with PowerView® Automation and Custom Clutch operating systems. Optional valance design feature available.' },
        { image: 'page026_img04_479x623.jpeg', label: 'Front Shade Lowered, Back Liner Fully Raised' },
        { image: 'page026_img05_475x525.jpeg', label: 'Light-Filtering Liner', sublabel: 'Diffuses light for a soft glow while providing moderate privacy.' },
        { image: 'page026_img06_475x525.jpeg', label: 'Room-Darkening Liner', sublabel: 'Provides enhanced light control with maximum privacy.' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'PowerView® Automation',
      cols: 4,
      items: [
        { image: 'page027_img01_944x1955.jpeg', label: 'PowerView® Automation', sublabel: 'Program shadings to be in the best positions throughout the day. Remote control gives the illusion that you\'re always home.' },
        { image: 'page027_img02_321x556.jpeg', label: 'Convenience', sublabel: 'Achieve your perfect light automatically with scheduled shade adjustments.' },
        { image: 'page028_img08_711x602.jpeg', label: 'Scheduled Scenes', sublabel: 'Shades adjust automatically throughout the day — lower at bedtime for privacy and a perfect night\'s sleep.' },
        { image: 'page027_img06_471x341.jpeg', label: 'EasyRise®', sublabel: 'Raise or lower the shade with a continuous cord loop for simple, intuitive operation.' },
        { image: 'page027_img08_509x394.jpeg', label: 'LiteRise®', sublabel: 'The cordless system makes raising and lowering the shade easy. Simply push up to raise and pull down to lower.' },
        { image: 'page027_img09_471x341.jpeg', label: 'UltraGlide®', sublabel: 'The revolutionary retractable cord with constant cord length provides enhanced child safety.' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'Operating Systems',
      cols: 4,
      items: [
        { image: 'page029_img01_416x669.jpeg', label: 'PowerView® Automation', sublabel: 'Smoothly integrates with other smart-home systems for effortless whole-home control.' },
        { image: 'page029_img03_471x341.jpeg', label: 'UltraGlide®', sublabel: 'The revolutionary retractable cord with constant cord length provides enhanced safety.' },
        { image: 'page029_img04_469x555.jpeg', label: 'Independent Operable Liner', sublabel: 'Duo Liner: • Color faces room, white faces street' },
        { image: 'page029_img05_469x559.jpeg', label: 'Top-Down/Bottom-Up', sublabel: 'This shade feature offers a more versatile approach to light control. Open from the top or bottom for the perfect balance.' },
        { image: 'page029_img07_509x394.jpeg', label: 'LiteRise®', sublabel: 'The cordless system makes raising and lowering the shade easy. Simply push up to raise and pull down to lower.' },
        { image: 'page029_img08_471x398.jpeg', label: 'Two-On-One-Headrail', sublabel: 'The solution for extra wide windows and side by side windows. A single headrail provides a clean, unified look.' },
        { image: 'page029_img09_471x341.jpeg', label: 'EasyRise®', sublabel: 'Raise or lower the shade with a continuous cord loop. A universal cord tensioner attaches to the wall for safety.' },
      ],
    },
    {
      type: 'card-grid',
      title: 'Top Treatments',
      cols: 4,
      cards: [
        { image: 'page030_img01_471x570.jpeg', title: 'Headrail with Valance', desc: 'Available with the following operating systems: UltraGlide®, LiteRise®, EasyRise®. Valance height options: 6 ½", 8", 12", 16". EasyRise.' },
        { image: 'page030_img02_471x570.jpeg', title: 'Fabric-covered Headrail without Valance', desc: 'Available with the following operating systems: PowerView® Automation, UltraGlide, LiteRise, EasyRise.' },
        { image: 'page030_img03_472x571.jpeg', title: 'Fabric Wrapped Standard Bar', desc: 'Available with all operating systems. Fabric Wrapped Flat Bar Available with UltraGlide and EasyRise operating systems.' },
        { image: 'page030_img04_472x571.jpeg', title: 'Fabric Wrapped Flat Bar', desc: 'Available with UltraGlide and EasyRise operating systems.' },
        { image: 'page030_img05_471x570.jpeg', title: 'Stand-Alone Valance', desc: 'Option The fabric-wrapped valance provides a structured and tailored profile. Valance height options: 6 ½", 8".' },
        { image: 'page030_img06_471x570.jpeg', title: 'Flat Metal Bar', desc: 'Available with UltraGlide and EasyRise operating systems. Sewn in Hem and EasyRise operating systems.' },
        { image: 'page030_img07_471x570.jpeg', title: 'Sewn in Hem', desc: 'Available with PowerView Automation, UltraGlide and EasyRise operating systems.' },
      ],
    },
    {
      type: 'card-grid',
      title: 'Top Treatments',
      cols: 4,
      cards: [
        { image: 'page032_img01_472x319.jpeg', title: 'Small Square Cassette 2.0', desc: 'Conceals the fabric roll behind a modern, square fabric-wrapped cover. Available with the following operating systems: PowerView Automation, Custom Clutch, SoftTouch Motorization.' },
        { image: 'page032_img02_470x319.jpeg', title: 'Large Square Cassette 2.0', desc: 'Conceals the fabric roll behind a modern, square fabric- wrapped cover. Available with the following operating systems: PowerView® Automation, Custom Clutch, UltraGlide®, LiteRise®, SoftTouch Motorization.' },
        { image: 'page032_img03_470x320.jpeg', title: 'Fabric-Wrapped Standard Bar', desc: 'Available with all the operating systems. Fabric-Wrapped Flat Bar Clutch, UltraGlide, SoftTouch.' },
        { image: 'page032_img04_468x317.jpeg', title: 'Fabric-Wrapped Flat Bar', desc: 'Available with PowerView Automation, Custom Clutch, UltraGlide, SoftTouch.' },
        { image: 'page032_img05_471x319.jpeg', title: '4" Fascia', desc: 'The exposed metal valance covers the fabric roll providing an upscale, sleek contemporary look. Color options include 10 Custom Hardware Colors and Anodized. Available with the following operating' },
        { image: 'page032_img06_472x320.jpeg', title: '5¼" Pocket', desc: 'The fabric roll and operating system is completely enclosed and recessed into the ceiling. Color options include Anodized and White Tiara. Available with the following operating systems: PowerView' },
        { image: 'page032_img07_469x319.jpeg', title: 'Flat Metal Bar', desc: 'Available with PowerView Automation, Custom Clutch, UltraGlide. Sewn In Hem Available with Custom Clutch.' },
        { image: 'page032_img08_470x319.jpeg', title: 'Sewn In Hem', desc: 'Available with Custom Clutch.' },
        { image: 'page032_img09_472x319.jpeg', title: 'Stand-Alone Valance', desc: 'The fabric-wrapped valance provides a structured and tailored profile. Valance length options: 6½", 8".' },
      ],
    },
    {
      type: 'comparison-grid',
      title: 'Expert Design Consultation',
      cols: 3,
      items: [
        { image: 'page037_img01_483x452.jpeg', label: 'In-Home Consultation', sublabel: 'Our expert designers help you find the perfect window treatment for your space.' },
        { image: 'page037_img02_483x454.jpeg', label: 'Custom Measurements', sublabel: 'Precise measurements ensure a perfect fit for every window.' },
        { image: 'page037_img03_483x454.jpeg', label: 'Professional Installation', sublabel: 'Expert installation for a flawless finished look.' },
      ],
    },
  ],

  gallery: [
    { image: 'page002_img01_2028x1953.jpeg', text: 'Alustra® Woven Textures®', label: '' },
    { image: 'page006_img01_2681x1953.jpeg', text: 'Fabric Timberlake · Color Sun', label: 'Operating System PowerView® Automation · Deck 1' },
    { image: 'page009_img03_1795x1732.jpeg', text: 'Imagine. Edit. Refine.', label: 'Fabric Ramble by Lori Weitzner · Color Silver' },
    { image: 'page020_img02_1762x1536.jpeg', text: 'Refined Dimension', label: 'Fabric Highlands by Lori Weitzner · Color Parchment' },
    { image: 'page021_img02_1703x1537.jpeg', text: 'Minimalistic Perspective', label: 'Fabric Retreat · Color Pure' },
    { image: 'page027_img07_1269x1243.jpeg', text: 'PowerView® Automation', label: 'Fabric Plantation · Color Dynasty' },
  ],

  hardwareColors: {
    type: 'hardware-colors',
    title: 'Hardware Color Guide',
    brandLabel: 'Alustra® Woven Textures®',
    items: [
      { image: 'page045_img01_306x306.jpeg', label: '048 Black' },
      { image: 'page045_img04_306x306.jpeg', label: '064 Bronze' },
      { image: 'page045_img05_306x306.jpeg', label: '235 Gold' },
      { image: 'page045_img06_306x306.jpeg', label: '316 Nickel' },
      { image: 'page045_img07_306x306.jpeg', label: '320 Rich Cream' },
      { image: 'page045_img08_306x306.jpeg', label: '651 Duchess Grey' },
      { image: 'page045_img09_306x306.jpeg', label: '879 Pearl Gray' },
    ],
  },

  swatchCollections: [
    {
      name: 'Fabrics',
      swatches: [
        { image: 'page012_img01_1787x1956.jpeg', colorName: 'Artisan · Calligraphy', specs: ['Operating System PowerView® Automation · Deck 2'] },
        { image: 'page013_img01_940x1956.jpeg', colorName: 'Coppice by Lori Weitzner · Sunrise', specs: ['Operating System Independent Operable Liner with PowerView® Automation · Deck 1'] },
        { image: 'page014_img02_1794x1952.jpeg', colorName: 'Retreat · Cabana', specs: ['Operating System Dual Roller with PowerView® Automation · Deck 1'] },
        { image: 'page015_img02_1793x1952.jpeg', colorName: 'Arusha · Journey', specs: ['Operating System Duolite® with PowerView® Automation · Deck 1'] },
        { image: 'page016_img01_1797x1953.jpeg', colorName: 'Lisban · Heritage', specs: ['Operating System PowerView® Automation · Deck 2'] },
        { image: 'page017_img02_1795x1957.jpeg', colorName: 'Rivulet by Lori Weitzner · Silt', specs: ['Operating System PowerView® Automation · Deck 1'] },
        { image: 'page036_img01_1749x1880.jpeg', colorName: 'Primitive · Concrete', specs: ['Operating System PowerView® Automation · Deck 2'] },
        { image: 'page046_img01_632x1050.jpeg', colorName: 'SNOW', specs: ['Sheer RMB-100'] },
        { image: 'page046_img02_632x1050.jpeg', colorName: 'SILVER', specs: ['Sheer RMB-300'] },
        { image: 'page047_img01_632x1050.jpeg', colorName: 'PEWTER', specs: ['Sheer RMB-800'] },
        { image: 'page048_img01_632x1050.jpeg', colorName: 'WHISP', specs: ['Sheer COP-700'] },
        { image: 'page048_img02_632x1050.jpeg', colorName: 'FLINT', specs: ['Sheer COP-800'] },
        { image: 'page049_img01_632x1050.jpeg', colorName: 'SUNRISE', specs: ['Sheer COP-350'] },
        { image: 'page050_img01_632x1050.jpeg', colorName: 'JOURNEY', specs: ['Sheer ARU-300'] },
        { image: 'page050_img02_632x1050.jpeg', colorName: 'PLATEAU', specs: ['Sheer ARU-301'] },
        { image: 'page051_img01_632x1050.jpeg', colorName: 'PATH', specs: ['Sheer ARU-400'] },
        { image: 'page051_img02_632x1050.jpeg', colorName: 'BOUNDLESS', specs: ['Sheer ARU-800'] },
        { image: 'page052_img01_632x1050.jpeg', colorName: 'WHITE SAIL', specs: ['Semi-Sheer CPR-100'] },
        { image: 'page052_img02_632x1050.jpeg', colorName: 'PARADISE', specs: ['Semi-Sheer CPR-200'] },
        { image: 'page053_img01_632x1050.jpeg', colorName: 'BREEZE', specs: ['Semi-Sheer CPR-800'] },
        { image: 'page053_img02_632x1050.jpeg', colorName: 'BUNGALOW', specs: ['Semi-Sheer CPR-801'] },
        { image: 'page054_img01_632x1050.jpeg', colorName: 'HAMMOCK', specs: ['Semi-Sheer CPR-400'] },
        { image: 'page055_img01_632x1050.jpeg', colorName: 'CAPELLA', specs: ['Semi-Sheer LYR-100'] },
        { image: 'page055_img02_632x1050.jpeg', colorName: 'HARMONY', specs: ['Semi-Sheer LYR-200'] },
        { image: 'page056_img01_632x1050.jpeg', colorName: 'CAPRICE', specs: ['Semi-Sheer LYR-800'] },
        { image: 'page056_img02_632x1050.jpeg', colorName: 'CANTATA', specs: ['Semi-Sheer LYR-700'] },
        { image: 'page057_img01_632x1050.jpeg', colorName: 'PAPYRUS', specs: ['Semi-Sheer TBL-200'] },
        { image: 'page057_img02_632x1050.jpeg', colorName: 'SUN', specs: ['Semi-Sheer TBL-300'] },
        { image: 'page058_img01_632x1050.jpeg', colorName: 'HONEY', specs: ['Semi-Sheer TBL-402'] },
        { image: 'page058_img02_632x1050.jpeg', colorName: 'TOASTED PECAN', specs: ['Semi-Sheer TBL-401'] },
        { image: 'page059_img01_632x1050.jpeg', colorName: 'COCOA', specs: ['Semi-Sheer TBL-400'] },
        { image: 'page060_img01_632x1050.jpeg', colorName: 'SOAPSTONE', specs: ['Semi-Sheer RVL-300'] },
        { image: 'page060_img02_632x1050.jpeg', colorName: 'BUTTERSCOTCH', specs: ['Semi-Sheer RVL-400'] },
        { image: 'page061_img01_632x1050.jpeg', colorName: 'SILT', specs: ['Semi-Sheer RVL-700'] },
        { image: 'page062_img01_632x1050.jpeg', colorName: 'PURE', specs: ['Semi-Sheer RE-101'] },
        { image: 'page062_img02_632x1050.jpeg', colorName: 'COZY', specs: ['Semi-Sheer RE-300'] },
        { image: 'page063_img01_632x1050.jpeg', colorName: 'JOY', specs: ['Semi-Sheer RE-800'] },
        { image: 'page063_img02_632x1050.jpeg', colorName: 'CABANA', specs: ['Semi-Sheer RE-400'] },
        { image: 'page064_img01_632x1050.jpeg', colorName: 'GLASSINE', specs: ['Semi-Sheer FO-100'] },
        { image: 'page064_img02_632x1050.jpeg', colorName: 'ABALONE', specs: ['Semi-Sheer FO-822'] },
        { image: 'page065_img01_632x1050.jpeg', colorName: 'SHUTTER', specs: ['Semi-Sheer FO-800'] },
        { image: 'page065_img02_632x1050.jpeg', colorName: 'CAFE', specs: ['Semi-Sheer FO-329'] },
        { image: 'page066_img01_632x1050.jpeg', colorName: 'CAVIAR', specs: ['Semi-Sheer FO-900'] },
        { image: 'page067_img01_632x1050.jpeg', colorName: 'TIN', specs: ['Semi-Sheer LC-307'] },
        { image: 'page067_img02_632x1050.jpeg', colorName: 'CHROME', specs: ['Semi-Sheer LC-805'] },
        { image: 'page068_img01_632x1050.jpeg', colorName: 'PARCHMENT', specs: ['Semi-Opaque HLD-200'] },
        { image: 'page068_img02_632x1050.jpeg', colorName: 'LATTE', specs: ['Semi-Opaque HLD-300'] },
        { image: 'page069_img01_632x1050.jpeg', colorName: 'BROWN SUGAR', specs: ['Semi-Opaque HLD-400'] },
        { image: 'page070_img01_632x1050.jpeg', colorName: 'CHATEAU', specs: ['Semi-Opaque PLN-100'] },
        { image: 'page070_img02_632x1050.jpeg', colorName: 'NOBLE', specs: ['Semi-Opaque PLN-800'] },
        { image: 'page071_img01_632x1050.jpeg', colorName: 'DYNASTY', specs: ['Semi-Opaque PLN-801'] },
        { image: 'page071_img02_632x1050.jpeg', colorName: 'MONARCH', specs: ['Semi-Opaque PLN-300'] },
        { image: 'page072_img01_632x1050.jpeg', colorName: 'COFFEE', specs: ['Semi-Opaque PLN-400'] },
        { image: 'page073_img01_632x1050.jpeg', colorName: 'CANVAS', specs: ['Semi-Opaque ASN-300'] },
        { image: 'page073_img02_632x1050.jpeg', colorName: 'BATIK', specs: ['Semi-Opaque ASN-800'] },
        { image: 'page074_img01_632x1050.jpeg', colorName: 'SCULPT', specs: ['Semi-Opaque ASN-400'] },
        { image: 'page074_img02_632x1050.jpeg', colorName: 'CALLIGRAPHY', specs: ['Semi-Opaque ASN-900'] },
        { image: 'page075_img01_632x1050.jpeg', colorName: 'COBBLESTONE', specs: ['Semi-Opaque LSB-300'] },
        { image: 'page075_img02_632x1050.jpeg', colorName: 'COACH', specs: ['Semi-Opaque LSB-800'] },
        { image: 'page076_img01_632x1050.jpeg', colorName: 'SUNSET', specs: ['Semi-Opaque LSB-400'] },
        { image: 'page076_img02_632x1050.jpeg', colorName: 'CARRIAGE', specs: ['Semi-Opaque LSB-401'] },
        { image: 'page077_img01_632x1050.jpeg', colorName: 'HERITAGE', specs: ['Semi-Opaque LSB-900'] },
        { image: 'page078_img01_632x1050.jpeg', colorName: 'WHITEWASHED', specs: ['Semi-Opaque PM-206'] },
        { image: 'page078_img02_632x1050.jpeg', colorName: 'CONCRETE', specs: ['Semi-Opaque PM-205'] },
        { image: 'page079_img01_632x1050.jpeg', colorName: 'VINTAGE', specs: ['Semi-Opaque PM-300'] },
        { image: 'page079_img02_632x1050.jpeg', colorName: 'WEATHERVANE', specs: ['Semi-Opaque PM-404'] },
        { image: 'page080_img01_632x1050.jpeg', colorName: 'WHITE OAK', specs: ['Semi-Opaque EN-200'] },
        { image: 'page080_img02_632x1050.jpeg', colorName: 'BIRCH', specs: ['Semi-Opaque EN-802'] },
        { image: 'page081_img01_632x1050.jpeg', colorName: 'BRANCH', specs: ['Semi-Opaque EN-302'] },
        { image: 'page081_img02_632x1050.jpeg', colorName: 'TWIG', specs: ['Semi-Opaque EN-351'] },
        { image: 'page082_img01_632x1050.jpeg', colorName: 'RAFFIA', specs: ['Semi-Opaque ON-439'] },
        { image: 'page082_img02_632x1050.jpeg', colorName: 'PALM', specs: ['Semi-Opaque ON-701'] },
        { image: 'page083_img01_632x1050.jpeg', colorName: 'SIENNA', specs: ['Semi-Opaque ON-422'] },
        { image: 'page083_img02_632x1050.jpeg', colorName: 'RE-BARK', specs: ['Semi-Opaque ON-402'] },
        { image: 'page084_img01_632x1050.jpeg', colorName: 'SLATE', specs: ['Semi-Opaque ON-601'] },
      ],
    },
  ],

  cellSize: null,
  opacity: null,
  edgeBanding: null,
  liner: null,
}
