// AAPP-parity drapery finished-size recommendation.
//
// Ported 1:1 from AAPP `app-quotes-drapery.js` draperyRecommendSize (L400) +
// draperyResolveMeasurementContext (L355). Frozen expectations in
// draperyRecommend.test.ts were generated by executing the ORIGINAL AAPP
// source in node (2026-07-19) — if a test fails, the two sides drifted; fix
// the port, never the numbers. Recon write-up:
// docs/AAPP-recon-shutter-pricing-drapery-size-2026-07-19.md.
//
// Parity quirks preserved on purpose:
// - A left/right clearance of 0 means "not measured" and is treated as
//   UNLIMITED (Infinity), not zero.
// - Floor-to-ceiling = min of measured wall heights; when no wall height was
//   measured it is derived as clearBottom + windowHeight + clearTop.
// - Wall-rod height adds gap/2 ONLY when no wall height was measured and the
//   window-top-to-ceiling gap is between 20" and 40".
// - Width rounds to whole inches, height to 1/4".

export const DRAPERY_RIPPLE_PARAMS = {
  cn_6cm: { pulley: 2.3622, button: 4.9213 },
  cn_7cm: { pulley: 2.76, button: 5.7087 },
  us_60: { pulley: 2.625, button: 4.25 },
  us_80: { pulley: 2.375, button: 4.25 },
  us_100: { pulley: 2.125, button: 4.25 },
  us_120: { pulley: 1.875, button: 4.25 },
} as const

export type RippleStyleKey = keyof typeof DRAPERY_RIPPLE_PARAMS

function ceilingToEven(x: number): number {
  const n = Math.ceil(x)
  return n % 2 === 1 ? n + 1 : n
}

/** AAPP "二舍三入": fraction < 0.3 rounds down, otherwise up. */
function twoSheThreeJin(x: number): number {
  const i = Math.floor(x)
  const d = x - i
  return d < 0.3 ? i : i + 1
}

export interface DraperyHardwareSpace {
  /** Rod return depth per side (in). */
  returnIn?: number
  leftFinialLengthIn?: number
  rightFinialLengthIn?: number
  /** Vertical clearance the hardware itself consumes (in). */
  maxCurtainHeightOffsetIn?: number
}

export interface DraperyRecommendInput {
  /** Window width (outer-frame preferred, AAPP uses outer > inner). */
  windowWidthIn: number
  windowHeightIn: number
  /** Wall clearance beyond the window per side; 0/undefined = not measured (unlimited). */
  clearLeftIn?: number
  clearRightIn?: number
  /** Window top → ceiling (in). */
  clearTopIn?: number
  /** Window bottom → floor (in). */
  clearBottomIn?: number
  /** Measured floor-to-ceiling heights (L/C/R); min wins. Empty = derive from window + clearances. */
  wallHeightsIn?: number[]
  /** Hem-off-the-floor clearance; AAPP default 0.5". */
  clearanceFromFloorIn?: number
  rodType?: 'motorized_ceiling_track' | 'ceiling_track' | 'wall_rod'
  operation?: 'split' | 'single_left' | 'single_right'
  styleFamily?: 'pleated' | 'ripple'
  /** Ripple carrier spec; AAPP default cn_6cm. */
  rippleStyleKey?: RippleStyleKey
  /** Present = hardware configured (AAPP: hw.enabled && profileKey). */
  hardware?: DraperyHardwareSpace
}

export interface DraperyRecommendResult {
  recommendedFinishedWidthIn: number | null
  recommendedFinishedHeightIn: number | null
}

export function recommendDraperySize(input: DraperyRecommendInput): DraperyRecommendResult | null {
  const W = Number(input.windowWidthIn) || 0
  const H = Number(input.windowHeightIn) || 0
  if (!W || !H) return null

  const clearL = Number(input.clearLeftIn) || 0
  const clearR = Number(input.clearRightIn) || 0
  const clearT = Number(input.clearTopIn) || 0
  const clearB = Number(input.clearBottomIn) || 0
  const floor = input.clearanceFromFloorIn != null ? Number(input.clearanceFromFloorIn) : 0.5

  const wallHts = (input.wallHeightsIn || []).filter((v) => Number(v) > 0).map(Number)
  const floorToCeiling = wallHts.length > 0 ? Math.min(...wallHts) : clearB + H + clearT
  const hasWallHeight = wallHts.length > 0

  const sf = input.styleFamily || ''
  const op = input.operation || ''
  const sk: RippleStyleKey = input.rippleStyleKey || 'cn_6cm'
  const rodType = input.rodType || 'ceiling_track'

  // Unmeasured (0) side clearance = unlimited.
  const L = clearL > 0 ? clearL : Infinity
  const R = clearR > 0 ? clearR : Infinity
  const T = isFinite(L) && isFinite(R) ? W + L + R : Infinity
  const H_fc = floorToCeiling
  const H_wc = clearT

  // Hardware return + finial deduction per side.
  const hw = input.hardware
  const hwEnabled = !!hw
  const hwReturn = hwEnabled ? (hw!.returnIn != null ? Number(hw!.returnIn) : 0) : 0
  const hwFinialL = hwEnabled ? hw!.leftFinialLengthIn || 0 : 0
  const hwFinialR = hwEnabled ? hw!.rightFinialLengthIn || 0 : 0
  const leftHwSpace = hwReturn + hwFinialL
  const rightHwSpace = hwReturn + hwFinialR
  const T_avail = isFinite(T) ? T - leftHwSpace - rightHwSpace : Infinity

  let recW: number | null = null

  if (sf === 'pleated') {
    if (op === 'split') {
      // Iterative: stack width is a function of the FINISHED width, so solve
      // F = W + 2·stack(F) by fixed-point iteration (≤15 rounds).
      let F = W
      for (let iter = 0; iter < 15; iter++) {
        const bcT = twoSheThreeJin((F * 3) / 55)
        const bcS = bcT / 2
        const plts = Math.floor(bcS) * 5 + (bcS % 1 >= 0.4 ? 2 : 0)
        const Sn = plts * 0.7
        const Fn = W + 2 * Sn
        if (Math.abs(Fn - F) < 0.05) {
          F = Fn
          break
        }
        F = Fn
      }
      const S_final = (F - W) / 2
      recW = S_final > L || S_final > R || F > T_avail ? T_avail - 1 : F
    } else {
      // One-way: target 24" of stack on the opening side, limited by clearance.
      const stackSide = op === 'single_left' ? L : R
      const base = W + Math.min(24, Math.max(stackSide, 0))
      let F2 = base
      for (let iter2 = 0; iter2 < 10; iter2++) {
        const bcT2 = twoSheThreeJin((F2 * 3) / 55)
        const bcS2 = bcT2 // all panels stack to one side
        const plts2 = Math.floor(bcS2) * 5 + (bcS2 % 1 >= 0.4 ? 2 : 0)
        const Sn2 = plts2 * 0.7
        const Fn2 = W + Math.min(Sn2, stackSide > 0 ? stackSide : Sn2)
        if (Math.abs(Fn2 - F2) < 0.05) {
          F2 = Fn2
          break
        }
        F2 = Fn2
      }
      recW = F2 > T_avail - 1 ? T_avail - 1 : F2
    }
  } else if (sf === 'ripple') {
    const rp = DRAPERY_RIPPLE_PARAMS[sk] || DRAPERY_RIPPLE_PARAMS.cn_6cm
    const P = rp.pulley
    const K = 0.66
    const C = 3.0
    if (op === 'split') {
      // Carriers span the window when closed → N from window width.
      const nRaw = W / (2 * (P - K))
      const N = ceilingToEven(nRaw)
      const S2 = N * K + C
      const fT2 = 2 * (N * P + C)
      recW = S2 > L || S2 > R || fT2 > T_avail ? T_avail - 1 : fT2
    } else {
      let base3 = W + 24
      const ss3 = op === 'single_left' ? L : R
      if (base3 > T_avail - 1) base3 = T_avail - 1
      recW = ss3 < 24 ? Math.min(W + ss3, T_avail - 1) : base3
    }
  }

  // Height recommendation.
  let recH: number
  const hwHeightOffset = hwEnabled && hw!.maxCurtainHeightOffsetIn != null ? Number(hw!.maxCurtainHeightOffsetIn) : 0
  if (rodType === 'motorized_ceiling_track') {
    recH = H_fc - 1.25 - floor - hwHeightOffset
  } else if (rodType === 'ceiling_track') {
    recH = H_fc - 0.8 - floor - hwHeightOffset
  } else {
    // Wall/floor-mounted rod: 4" below ceiling; mid-mount when the gap is
    // 20–40" and no wall height was measured.
    const baseH = H_fc - 4.0 - floor - hwHeightOffset
    recH = !hasWallHeight && H_wc >= 20 && H_wc <= 40 ? baseH + H_wc / 2 : baseH
  }

  return {
    recommendedFinishedWidthIn: recW != null && isFinite(recW) ? Math.round(recW) : null,
    recommendedFinishedHeightIn: Math.round(recH * 4) / 4,
  }
}

// ── Height-only recommendation ───────────────────────────────────────────────
// For customers who measured the ceiling but not the window (chat wizard G5
// case, 2026-07-20): finished HEIGHT depends only on floor-to-ceiling, rod
// type, and floor clearance — same constants as recommendDraperySize above
// (kept in one place so the two can never drift). Width still requires the
// window size. Wall-rod mid-mount needs the window-top-to-ceiling gap, so the
// gap-adjustment branch is intentionally NOT applied here (no window height
// available); callers pass a measured wall height, which matches the engine's
// hasWallHeight branch anyway.

export interface FinishedHeightOnlyInput {
  /** Measured floor-to-ceiling heights (L/C/R); min wins. */
  wallHeightsIn: number[]
  rodType?: 'motorized_ceiling_track' | 'ceiling_track' | 'wall_rod'
  /** Hem-off-the-floor clearance; AAPP default 0.5". */
  clearanceFromFloorIn?: number
}

export function recommendFinishedHeightOnly(input: FinishedHeightOnlyInput): number | null {
  const wallHts = (input.wallHeightsIn || []).filter((v) => Number(v) > 0).map(Number)
  if (wallHts.length === 0) return null
  const H_fc = Math.min(...wallHts)
  const floor = input.clearanceFromFloorIn != null ? Number(input.clearanceFromFloorIn) : 0.5
  const rodType = input.rodType || 'ceiling_track'
  let recH: number
  if (rodType === 'motorized_ceiling_track') {
    recH = H_fc - 1.25 - floor
  } else if (rodType === 'ceiling_track') {
    recH = H_fc - 0.8 - floor
  } else {
    recH = H_fc - 4.0 - floor
  }
  return Math.round(recH * 4) / 4
}
