// GENERATED by apps/web/scripts/build-hardware-catalog.mjs from a dump of
// AAPP library.draperyHardwareCatalog. Do not edit by hand — regenerate.
//
// WHAT IS AND ISN'T HERE
// Taxonomy, every selectable colour, and every finial each profile allows.
// Deliberately NO PRICES: every figure comes from AAPP at request time
// (variant `drapery_hardware`), so this table can never drift from a real
// quote. It exists only because AAPP's `_priceDraperyHardware` rejects a call
// with a bare `missing_profile` — no list of what it would accept — and
// `libraryExport` doesn't ship the catalog.
//
// THREE THINGS THE ENGINE MADE US LEARN THE HARD WAY:
//  1. `colorKey` is REQUIRED whenever the profile has a palette, but it feeds
//     NO price maths — it is a pure validation gate.
//  2. `isTrackType` is FALSE for every H-rail, so classifying "pole vs track"
//     off that flag puts H-rails on the pole side. We classify by FAMILY.
//  3. Some profiles carry no price at all and AAPP answers `missing_price`.
//     We do NOT pre-filter those: callers try every matching profile and let
//     the failures drop out, so the day someone fills those prices in,
//     quoting starts working with no code change here.

export interface HardwareChoice {
  key: string
  label: string
}

export interface HardwareProfileRow {
  key: string
  family: string
  /** What a customer would call it. H-rails count as tracks. */
  kind: 'pole' | 'track'
  mount: 'wall' | 'ceiling'
  layer: 'single' | 'double'
  motorized: boolean
  /** Poles and H-rails take finials; tracks do not. */
  canHaveFinial: boolean
  /** AAPP's own displayName — safe to show a customer. */
  label: string
  /** Every colour AAPP will accept for this profile. Price-neutral. */
  colors: HardwareChoice[]
  /** Finials this profile allows. Each one AAPP prices separately. */
  finials: HardwareChoice[]
}

export const HARDWARE_PROFILES: HardwareProfileRow[] = [
  {
    key: "aluminum_ceiling_track_double", family: "aluminum_ceiling_track", kind: "track", mount: "ceiling",
    layer: "double", motorized: false, canHaveFinial: false,
    label: "Double Track",
    colors: [{"key":"White","label":"White"},{"key":"Black","label":"Black"}],
    finials: [],
  },
  {
    key: "aluminum_ceiling_track_single", family: "aluminum_ceiling_track", kind: "track", mount: "ceiling",
    layer: "single", motorized: false, canHaveFinial: false,
    label: "Single Track",
    colors: [{"key":"White","label":"White"},{"key":"Black","label":"Black"}],
    finials: [],
  },
  {
    key: "aluminum_track_double_wall", family: "aluminum_track", kind: "track", mount: "wall",
    layer: "double", motorized: false, canHaveFinial: false,
    label: "Double Track",
    colors: [{"key":"White","label":"White"},{"key":"Black","label":"Black"}],
    finials: [],
  },
  {
    key: "aluminum_track_single_wall", family: "aluminum_track", kind: "track", mount: "wall",
    layer: "single", motorized: false, canHaveFinial: false,
    label: "Single Track",
    colors: [{"key":"White","label":"White"},{"key":"Black","label":"Black"}],
    finials: [],
  },
  {
    key: "ceiling_h_rail_double", family: "ceiling_h_rail", kind: "track", mount: "ceiling",
    layer: "double", motorized: false, canHaveFinial: true,
    label: "Double H-Rail",
    colors: [{"key":"Matte Black","label":"Matte Black"},{"key":"Satin Nickel","label":"Satin Nickel"},{"key":"Antique Pewter","label":"Antique Pewter"},{"key":"Satin Gold","label":"Satin Gold"},{"key":"Brushed Nickel","label":"Brushed Nickel"},{"key":"Old Gold","label":"Old Gold"}],
    finials: [{"key":"ball_finial","label":"Ball Finial"},{"key":"torpedo_finial","label":"Torpedo Finial"},{"key":"ring_finial","label":"Ring End / No Finial"}],
  },
  {
    key: "ceiling_h_rail_single", family: "ceiling_h_rail", kind: "track", mount: "ceiling",
    layer: "single", motorized: false, canHaveFinial: true,
    label: "Single H-Rail",
    colors: [{"key":"Matte Black","label":"Matte Black"},{"key":"Satin Nickel","label":"Satin Nickel"},{"key":"Antique Pewter","label":"Antique Pewter"},{"key":"Satin Gold","label":"Satin Gold"},{"key":"Brushed Nickel","label":"Brushed Nickel"},{"key":"Old Gold","label":"Old Gold"}],
    finials: [{"key":"ball_finial","label":"Ball Finial"},{"key":"torpedo_finial","label":"Torpedo Finial"},{"key":"ring_finial","label":"Ring End / No Finial"}],
  },
  {
    key: "h_rail_double_1_3_8_1_1_8_wall", family: "h_rail", kind: "track", mount: "wall",
    layer: "double", motorized: false, canHaveFinial: true,
    label: "Double H-Rail (1 3/8\" + 1 1/8\")",
    colors: [{"key":"Matte Black","label":"Matte Black"},{"key":"Satin Nickel","label":"Satin Nickel"},{"key":"Antique Pewter","label":"Antique Pewter"},{"key":"Satin Gold","label":"Satin Gold"},{"key":"Brushed Nickel","label":"Brushed Nickel"},{"key":"Old Gold","label":"Old Gold"}],
    finials: [{"key":"ball_finial","label":"Ball Finial"},{"key":"torpedo_finial","label":"Torpedo Finial"},{"key":"disc_finial","label":"Disc Finial"},{"key":"crystal_finial","label":"Crystal Finial"},{"key":"ring_finial","label":"Ring End / No Finial"}],
  },
  {
    key: "h_rail_double_1_3_8_1_3_8_wall", family: "h_rail", kind: "track", mount: "wall",
    layer: "double", motorized: false, canHaveFinial: true,
    label: "Double H-Rail (1 3/8\" + 1 3/8\")",
    colors: [{"key":"Matte Black","label":"Matte Black"},{"key":"Satin Nickel","label":"Satin Nickel"},{"key":"Antique Pewter","label":"Antique Pewter"},{"key":"Satin Gold","label":"Satin Gold"},{"key":"Brushed Nickel","label":"Brushed Nickel"},{"key":"Old Gold","label":"Old Gold"}],
    finials: [{"key":"ball_finial","label":"Ball Finial"},{"key":"torpedo_finial","label":"Torpedo Finial"},{"key":"disc_finial","label":"Disc Finial"},{"key":"crystal_finial","label":"Crystal Finial"},{"key":"ring_finial","label":"Ring End / No Finial"}],
  },
  {
    key: "h_rail_single_1_1_8_wall", family: "h_rail", kind: "track", mount: "wall",
    layer: "single", motorized: false, canHaveFinial: true,
    label: "Single H-Rail 1 1/8\"",
    colors: [{"key":"Matte Black","label":"Matte Black"},{"key":"Satin Nickel","label":"Satin Nickel"},{"key":"Antique Pewter","label":"Antique Pewter"},{"key":"Satin Gold","label":"Satin Gold"},{"key":"Brushed Nickel","label":"Brushed Nickel"},{"key":"Old Gold","label":"Old Gold"}],
    finials: [{"key":"ball_finial","label":"Ball Finial"},{"key":"torpedo_finial","label":"Torpedo Finial"},{"key":"disc_finial","label":"Disc Finial"},{"key":"crystal_finial","label":"Crystal Finial"},{"key":"ring_finial","label":"Ring End / No Finial"}],
  },
  {
    key: "h_rail_single_1_3_8_wall", family: "h_rail", kind: "track", mount: "wall",
    layer: "single", motorized: false, canHaveFinial: true,
    label: "Single H-Rail 1 3/8\"",
    colors: [{"key":"Matte Black","label":"Matte Black"},{"key":"Satin Nickel","label":"Satin Nickel"},{"key":"Antique Pewter","label":"Antique Pewter"},{"key":"Satin Gold","label":"Satin Gold"},{"key":"Brushed Nickel","label":"Brushed Nickel"},{"key":"Old Gold","label":"Old Gold"}],
    finials: [{"key":"ball_finial","label":"Ball Finial"},{"key":"torpedo_finial","label":"Torpedo Finial"},{"key":"disc_finial","label":"Disc Finial"},{"key":"crystal_finial","label":"Crystal Finial"},{"key":"ring_finial","label":"Ring End / No Finial"}],
  },
  {
    key: "metal_rod_double_1_3_8_1_1_8_wall", family: "metal_rod", kind: "pole", mount: "wall",
    layer: "double", motorized: false, canHaveFinial: true,
    label: "Double Metal Rod (1 3/8\" + 1 1/8\")",
    colors: [{"key":"Matte Black","label":"Matte Black"},{"key":"Satin Nickel","label":"Satin Nickel"},{"key":"Antique Pewter","label":"Antique Pewter"},{"key":"Satin Gold","label":"Satin Gold"},{"key":"Brushed Nickel","label":"Brushed Nickel"},{"key":"Old Gold","label":"Old Gold"}],
    finials: [{"key":"ball_finial","label":"Ball Finial"},{"key":"torpedo_finial","label":"Torpedo Finial"},{"key":"disc_finial","label":"Disc Finial"},{"key":"crystal_finial","label":"Crystal Finial"},{"key":"ring_finial","label":"Ring End / No Finial"}],
  },
  {
    key: "metal_rod_double_1_3_8_1_3_8_wall", family: "metal_rod", kind: "pole", mount: "wall",
    layer: "double", motorized: false, canHaveFinial: true,
    label: "Double Metal Rod (1 3/8\" + 1 3/8\")",
    colors: [{"key":"Matte Black","label":"Matte Black"},{"key":"Satin Nickel","label":"Satin Nickel"},{"key":"Antique Pewter","label":"Antique Pewter"},{"key":"Satin Gold","label":"Satin Gold"},{"key":"Brushed Nickel","label":"Brushed Nickel"},{"key":"Old Gold","label":"Old Gold"}],
    finials: [{"key":"ball_finial","label":"Ball Finial"},{"key":"torpedo_finial","label":"Torpedo Finial"},{"key":"disc_finial","label":"Disc Finial"},{"key":"crystal_finial","label":"Crystal Finial"},{"key":"ring_finial","label":"Ring End / No Finial"}],
  },
  {
    key: "metal_rod_single_1_1_8_wall", family: "metal_rod", kind: "pole", mount: "wall",
    layer: "single", motorized: false, canHaveFinial: true,
    label: "Single Metal Rod 1 1/8\"",
    colors: [{"key":"Matte Black","label":"Matte Black"},{"key":"Satin Nickel","label":"Satin Nickel"},{"key":"Antique Pewter","label":"Antique Pewter"},{"key":"Satin Gold","label":"Satin Gold"},{"key":"Brushed Nickel","label":"Brushed Nickel"},{"key":"Old Gold","label":"Old Gold"}],
    finials: [{"key":"ball_finial","label":"Ball Finial"},{"key":"torpedo_finial","label":"Torpedo Finial"},{"key":"disc_finial","label":"Disc Finial"},{"key":"crystal_finial","label":"Crystal Finial"},{"key":"ring_finial","label":"Ring End / No Finial"}],
  },
  {
    key: "metal_rod_single_1_3_8_wall", family: "metal_rod", kind: "pole", mount: "wall",
    layer: "single", motorized: false, canHaveFinial: true,
    label: "Single Metal Rod 1 3/8\"",
    colors: [{"key":"Matte Black","label":"Matte Black"},{"key":"Satin Nickel","label":"Satin Nickel"},{"key":"Antique Pewter","label":"Antique Pewter"},{"key":"Satin Gold","label":"Satin Gold"},{"key":"Brushed Nickel","label":"Brushed Nickel"},{"key":"Old Gold","label":"Old Gold"}],
    finials: [{"key":"ball_finial","label":"Ball Finial"},{"key":"torpedo_finial","label":"Torpedo Finial"},{"key":"disc_finial","label":"Disc Finial"},{"key":"crystal_finial","label":"Crystal Finial"},{"key":"ring_finial","label":"Ring End / No Finial"}],
  },
  {
    key: "motorized_ceiling_h_rail_double", family: "motorized_ceiling_h_rail", kind: "track", mount: "ceiling",
    layer: "double", motorized: true, canHaveFinial: false,
    label: "Double Motorized H-Rail",
    colors: [{"key":"Matte Black","label":"Matte Black"},{"key":"Satin Nickel","label":"Satin Nickel"},{"key":"Antique Pewter","label":"Antique Pewter"},{"key":"Satin Gold","label":"Satin Gold"},{"key":"Brushed Nickel","label":"Brushed Nickel"},{"key":"Old Gold","label":"Old Gold"}],
    finials: [],
  },
  {
    key: "motorized_ceiling_h_rail_single", family: "motorized_ceiling_h_rail", kind: "track", mount: "ceiling",
    layer: "single", motorized: true, canHaveFinial: false,
    label: "Single Motorized H-Rail",
    colors: [{"key":"Matte Black","label":"Matte Black"},{"key":"Satin Nickel","label":"Satin Nickel"},{"key":"Antique Pewter","label":"Antique Pewter"},{"key":"Satin Gold","label":"Satin Gold"},{"key":"Brushed Nickel","label":"Brushed Nickel"},{"key":"Old Gold","label":"Old Gold"}],
    finials: [],
  },
  {
    key: "motorized_ceiling_track_double", family: "motorized_ceiling_track", kind: "track", mount: "ceiling",
    layer: "double", motorized: true, canHaveFinial: false,
    label: "Double Track",
    colors: [{"key":"White","label":"White"}],
    finials: [],
  },
  {
    key: "motorized_ceiling_track_single", family: "motorized_ceiling_track", kind: "track", mount: "ceiling",
    layer: "single", motorized: true, canHaveFinial: false,
    label: "Single Track",
    colors: [{"key":"White","label":"White"}],
    finials: [],
  },
  {
    key: "motorized_h_rail_double", family: "motorized_h_rail", kind: "track", mount: "wall",
    layer: "double", motorized: true, canHaveFinial: false,
    label: "Double Motorized H-Rail",
    colors: [{"key":"Matte Black","label":"Matte Black"},{"key":"Satin Nickel","label":"Satin Nickel"},{"key":"Antique Pewter","label":"Antique Pewter"},{"key":"Satin Gold","label":"Satin Gold"},{"key":"Brushed Nickel","label":"Brushed Nickel"},{"key":"Old Gold","label":"Old Gold"}],
    finials: [],
  },
  {
    key: "motorized_h_rail_single", family: "motorized_h_rail", kind: "track", mount: "wall",
    layer: "single", motorized: true, canHaveFinial: false,
    label: "Single Motorized H-Rail",
    colors: [{"key":"Matte Black","label":"Matte Black"},{"key":"Satin Nickel","label":"Satin Nickel"},{"key":"Antique Pewter","label":"Antique Pewter"},{"key":"Satin Gold","label":"Satin Gold"},{"key":"Brushed Nickel","label":"Brushed Nickel"},{"key":"Old Gold","label":"Old Gold"}],
    finials: [],
  },
  {
    key: "motorized_track_double_wall", family: "motorized_track", kind: "track", mount: "wall",
    layer: "double", motorized: true, canHaveFinial: false,
    label: "Double Track",
    colors: [{"key":"White","label":"White"}],
    finials: [],
  },
  {
    key: "motorized_track_single_wall", family: "motorized_track", kind: "track", mount: "wall",
    layer: "single", motorized: true, canHaveFinial: false,
    label: "Single Track",
    colors: [{"key":"White","label":"White"}],
    finials: [],
  },
  {
    key: "wood_pole_double_2in_1_3_8_wall", family: "wood_pole", kind: "pole", mount: "wall",
    layer: "double", motorized: false, canHaveFinial: true,
    label: "Double Wood Pole (2\" + 1 3/8\")",
    colors: [{"key":"Black","label":"Black"},{"key":"Espresso","label":"Espresso"},{"key":"Gold","label":"Gold"},{"key":"Silver","label":"Silver"},{"key":"Walnut","label":"Walnut"}],
    finials: [{"key":"ball_finial","label":"Ball Finial"},{"key":"torpedo_finial","label":"New Finial"},{"key":"disc_finial","label":"2‘’ Fire Wood Finial"},{"key":"crystal_finial","label":"2‘’ UFO Wood Finial"},{"key":"ring_finial","label":"2‘’ Ring End"}],
  },
  {
    key: "wood_pole_single_1_3_8_wall", family: "wood_pole", kind: "pole", mount: "wall",
    layer: "single", motorized: false, canHaveFinial: true,
    label: "Single 1 3/8\" Wood Pole",
    colors: [{"key":"Black","label":"Black"},{"key":"Espresso","label":"Espresso"},{"key":"Gold","label":"Gold"},{"key":"Silver","label":"Silver"},{"key":"Walnut","label":"Walnut"}],
    finials: [{"key":"ball_finial","label":"Ball Finial"},{"key":"torpedo_finial","label":"New Finial"},{"key":"disc_finial","label":"2‘’ Fire Wood Finial"},{"key":"crystal_finial","label":"2‘’ UFO Wood Finial"},{"key":"ring_finial","label":"2‘’ Ring End"}],
  },
  {
    key: "wood_pole_single_2in_wall", family: "wood_pole", kind: "pole", mount: "wall",
    layer: "single", motorized: false, canHaveFinial: true,
    label: "Single 2\" Wood Pole",
    colors: [{"key":"Black","label":"Black"},{"key":"Espresso","label":"Espresso"},{"key":"Gold","label":"Gold"},{"key":"Silver","label":"Silver"},{"key":"Walnut","label":"Walnut"}],
    finials: [{"key":"ball_finial","label":"Ball Finial"},{"key":"torpedo_finial","label":"New Finial"},{"key":"disc_finial","label":"2‘’ Fire Wood Finial"},{"key":"crystal_finial","label":"2‘’ UFO Wood Finial"},{"key":"ring_finial","label":"2‘’ Ring End"}],
  },
]

/** Poles are never motorised in this catalog — used to skip a pointless
 *  question when the customer has already said "rod". */
export const POLE_FAMILIES = ["metal_rod","wood_pole"]

/** First colour for a profile — satisfies the engine's gate when the customer
 *  has not picked one. Price-neutral, so this is a default, not an assumption
 *  worth disclosing. */
export function defaultColorKey(profileKey: string): string | null {
  const row = HARDWARE_PROFILES.find((p) => p.key === profileKey)
  return row && row.colors.length ? row.colors[0].key : null
}
